import os
from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import FileResponse
from app.trust.rbac import require_permission, get_case_or_403
from app import config, db, custody
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter
from reportlab.graphics.barcode.qr import QrCodeWidget
from reportlab.graphics import renderPDF
from reportlab.graphics.shapes import Drawing

router = APIRouter()

@router.get("/api/cases/{case_id}/certificate")
def generate_certificate(case_id: str, user: dict = Depends(require_permission("audit:export"))):
    get_case_or_403(case_id, user)
    
    cert_dir = os.path.join(config.DATA_DIR, "certificates")
    os.makedirs(cert_dir, exist_ok=True)
    pdf_path = os.path.join(cert_dir, f"{case_id}_certificate.pdf")
    
    c = canvas.Canvas(pdf_path, pagesize=letter)
    c.drawString(100, 750, f"Section 63 Certificate - Case {case_id}")
    c.drawString(100, 730, "Part A: Custodian / Part B: Expert")
    
    with db.session() as conn:
        latest_anchor = conn.execute("SELECT merkle_root, key_id FROM audit_anchors ORDER BY seq_to DESC LIMIT 1").fetchone()
        
    merkle_root = latest_anchor["merkle_root"] if latest_anchor else "none"
    key_id = latest_anchor["key_id"] if latest_anchor else "none"

    # QR Code
    qrw = QrCodeWidget(f"{case_id}|{merkle_root}|{key_id}")
    b = qrw.getBounds()
    d = Drawing(100, 100, transform=[100/b[2],0,0,100/b[3],0,0])
    d.add(qrw)
    renderPDF.draw(d, c, 400, 650)
    
    c.drawString(100, 710, f"Latest Audit Root: {merkle_root}")
    c.drawString(100, 690, f"Signing Key ID: {key_id}")
    c.drawString(100, 50, "Generated by DigiPramaan Section 65B(4) System. Cryptographically sealed.")
    c.save()
    
    with db.session() as conn:
        custody.append(conn, actor=user["username"], action="certificate_generated", case_id=case_id, detail={"path": pdf_path})
        
    return FileResponse(pdf_path, filename=f"{case_id}_certificate.pdf")
